"""FastAPI backend for the Excel AI add-in, powered by Google ADK + Gemini.

  * serves the Office.js task pane from ``/public``
  * exposes ``POST /api/generate`` which runs the ADK agent and returns the
    structured ``{ explanation, actions }`` payload the task pane applies to the grid
  * uses ADK session memory (keyed by the client's ``sessionId``) so follow-up
    turns refine the same sheet — no need to replay the whole history each call
  * serves over HTTPS using the dev certs created by ``office-addin-dev-certs``
    (Office add-ins refuse to load over plain HTTP, even on localhost)

Run it with:  python server.py
"""

from __future__ import annotations

import json
import os
from pathlib import Path

from dotenv import load_dotenv
from fastapi import FastAPI, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse, RedirectResponse
from fastapi.staticfiles import StaticFiles
from google.adk.runners import Runner
from google.adk.sessions import InMemorySessionService
from google.genai import types

# ---------------------------------------------------------------------------
# Config + credentials. Load GOOGLE_API_KEY from the shared .env.
# ---------------------------------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent
load_dotenv(BASE_DIR / "my_agent" / ".env")
load_dotenv(BASE_DIR / ".env")  # optional project-level overrides

if not os.environ.get("GOOGLE_API_KEY"):
    raise SystemExit(
        "\n[FATAL] GOOGLE_API_KEY is not set.\n"
        "        Add it to my_agent/.env, e.g.:\n"
        '        GOOGLE_API_KEY="your_key_here"\n'
    )

# Import after env is loaded so the agent picks up the credentials.
from python_agent.agent import root_agent  # noqa: E402

APP_NAME = "excel_ai"
USER_ID = "excel-user"  # single-user local add-in; sessions separate the chats
PORT = int(os.environ.get("PORT", "3000"))

# Dev certs generated by `npx office-addin-dev-certs install`.
# Override with TLS_CERT / TLS_KEY env vars if needed.
CERT_DIR = Path.home() / ".office-addin-dev-certs"
TLS_CERT = os.environ.get("TLS_CERT", str(CERT_DIR / "localhost.crt"))
TLS_KEY = os.environ.get("TLS_KEY", str(CERT_DIR / "localhost.key"))

# ---------------------------------------------------------------------------
# One Runner + session service for the whole process. The session service holds
# each conversation's memory in-process, keyed by sessionId.
# ---------------------------------------------------------------------------
session_service = InMemorySessionService()
runner = Runner(agent=root_agent, app_name=APP_NAME, session_service=session_service)

app = FastAPI(title="Excel AI (Google ADK)")
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

# Serve the task pane + its assets.
app.mount("/public", StaticFiles(directory=str(BASE_DIR / "public")), name="public")


@app.get("/")
async def root() -> RedirectResponse:
    return RedirectResponse(url="/public/taskpane.html")


@app.get("/health")
async def health() -> dict:
    return {"ok": True, "model": root_agent.model}


async def _ensure_session(session_id: str) -> None:
    """Create the ADK session on first use; reuse it (and its memory) after."""
    existing = await session_service.get_session(
        app_name=APP_NAME, user_id=USER_ID, session_id=session_id
    )
    if existing is None:
        await session_service.create_session(
            app_name=APP_NAME, user_id=USER_ID, session_id=session_id
        )


@app.post("/api/generate")
async def generate(request: Request) -> JSONResponse:
    """Run one conversation turn and return { explanation, actions }.

    Body: { "sessionId": "<uuid>", "prompt": "<user message>" }
    """
    body = await request.json()
    prompt = (body.get("prompt") or "").strip()
    session_id = (body.get("sessionId") or "").strip()

    if not prompt:
        return JSONResponse({"error": "A non-empty 'prompt' is required."}, status_code=400)
    if not session_id:
        return JSONResponse({"error": "A 'sessionId' is required."}, status_code=400)

    await _ensure_session(session_id)

    new_message = types.Content(role="user", parts=[types.Part(text=prompt)])

    final_text: str | None = None
    try:
        async for event in runner.run_async(
            user_id=USER_ID, session_id=session_id, new_message=new_message
        ):
            if event.is_final_response() and event.content and event.content.parts:
                final_text = event.content.parts[0].text
    except Exception as err:  # noqa: BLE001 - surface a clean message to the client
        print(f"[error] agent run failed: {err}")
        return JSONResponse(
            {"error": "Failed to generate spreadsheet from the model."}, status_code=500
        )

    if not final_text:
        return JSONResponse({"error": "Model returned an empty response."}, status_code=502)

    try:
        parsed = json.loads(final_text)
    except json.JSONDecodeError:
        print(f"[error] model returned non-JSON: {final_text!r}")
        return JSONResponse({"error": "Model returned malformed JSON."}, status_code=502)

    explanation = parsed.get("explanation") or "Generated spreadsheet."
    actions = [
        a
        for a in (parsed.get("actions") or [])
        if isinstance(a, dict) and isinstance(a.get("cell"), str) and "value" in a
    ]
    return JSONResponse({"explanation": explanation, "actions": actions})


if __name__ == "__main__":
    import uvicorn

    if not (Path(TLS_CERT).exists() and Path(TLS_KEY).exists()):
        raise SystemExit(
            f"\n[FATAL] TLS cert/key not found:\n  {TLS_CERT}\n  {TLS_KEY}\n"
            "        Generate them with:  npx office-addin-dev-certs install\n"
        )

    print(f"\n  Excel AI (Google ADK) running at https://localhost:{PORT}")
    print(f"   Task pane:  https://localhost:{PORT}/public/taskpane.html")
    print(f"   Model:      {root_agent.model}\n")

    uvicorn.run(
        app,
        host="0.0.0.0",
        port=PORT,
        ssl_certfile=TLS_CERT,
        ssl_keyfile=TLS_KEY,
    )
