object Colors {
    const val excelGreen        = "#217346"
    const val excelGreenDark    = "#185c37"
    const val bannerFrom        = "#1f6e44"
    const val bannerTo          = "#12502f"
    const val iconGradientLight = "#5fd394"
    const val iconGradientDark  = "#1c7a49"
    const val white             = "#ffffff"
    const val text              = "#1a1a1a"
    const val muted             = "#6b7280"
    const val border            = "#e3e5e8"
    const val fieldBorder       = "#d9dbde"
    const val surface           = "#f3f4f6"
    const val suggestionHover   = "#f4f9f6"
    const val msgLabel          = "#2a2a2a"
    const val errorBg           = "#fdecea"
    const val errorBorder       = "#f5c6cb"
    const val errorText         = "#c0392b"
    const val placeholder       = "#9aa0a6"
    const val sendDisabled      = "#9bbfac"
    const val scrollThumb       = "#d4d6da"
    const val composerDivider   = "#ededed"
}
